name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-lint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2

      - name: Install luacheck
        run: |
          sudo apt install -y luarocks
          sudo luarocks install luacheck > build.log 2>&1 || (cat build.log && exit 1)

      - name: Setup Nodejs env
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '12'

      - name: Install eclint
        run: |
          sudo npm install -g eclint

      - name: Script
        run: |
          make lint

  misc-lint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.2

      - name: Spell check
        run: |
          pip install codespell==2.1.0
          git grep --cached -l '' | xargs codespell --ignore-words=.github/workflows/ignore_words

      - name: Merge conflict
        run: |
          grep "^<<<<<<< HEAD" $(git grep --cached -l '' | xargs) && exit 1 || true
